version: '3.9'
services:
  ruuter:
    container_name: ruuter
    image: ruuter
    volumes:
      - ./DSL/Ruuter:/DSL
    ports:
      - 8080:8080
    networks:
      - bykstack
  resql:
    container_name: resql
    image: resql
    environment:
      - sqlms.datasources.[0].name=byk
      - sqlms.datasources.[0].jdbcUrl=jdbc:postgresql://171.22.247.1:5433/byk
      - sqlms.datasources.[0].username=byk
      - sqlms.datasources.[0].password=1234
      - logging.level.org.springframework.boot=INFO
    ports:
      - 8082:8082
    volumes:
      - ./DSL/Resql:/workspace/app/templates/byk
    networks:
      - bykstack

networks:
  bykstack:
    name: bykstack
    driver: bridge